### ISSUE TITLE
Feature Request: Implement near-realtime energy consumption

### ISSUE THREAD

**Issue by Sebmaster** [tronikos/opower#24]
ConEd (#13) offers near-realtime (~4hr delay) energy consumption via a /usage endpoint. Request URL looks like this: `https://cned.opower.com/ei/edge/apis/cws-real-time-ami-v1/cws/cned/accounts/$uuid/meters/$utilityAccountId2/usage` and the request requires the regular Opower auth token. No other header trickery is required. The response body looks like this:

```json
{
  "unit": "KWH",
  "reads": [
    {
      "startTime": "2023-08-05T03:15:00-04:00",
      "endTime": "2023-08-05T03:30:00-04:00",
      "value": 0.093
    },
    [...]
  ]
}
```

Not sure how applicable this is to other utilities, but might be interesting to find out if that exists. I'm a bit busy, so don't currently have plans to implement this myself. Feel free to pick this up.

**Comment by rhdny** [comment]
I've been following tronikos' and your efforts in this. Thanks so much for putting the time in. There are a lot of ConEd customers who will be happy!

**Comment by tronikos** [comment]
My utility PG&E returns: `{"error":{"details":"No data returned from API."}}` so I have little incentive implementing this. I'll be happy accepting any PR here and in the core integration.

**Comment by rhdny** [comment]
I guess it's not common across all opower utilities. It's a cool feature for at least ConEd users that gets you closer to real-time usage. Wish they would do it with gas.

**Comment by akoebbe** [comment]
FWIW, I tried the URL pattern @Sebmaster found for my utility (Evergy), which seems to only have information up to the previous day (at the quarter hour granularity). I got this response:

URL: https://kcpk.opower.com/ei/edge/apis/cws-real-time-ami-v1/cws/kcpk/accounts/[My UUID]/meters/[My utilityAccountId2]/usage

```
{"error":{"details":"No data returned from API. (24814820-b153-4b8d-8e97-64f4f79e5451)"}}
```

I'm guessing Evergy either isn't sending the data over for that or they don't have that tier of service with Oracle. :shrug:

**Comment by rhdny** [comment]
ConEd highlights the real-time usage feature via the UI. I'd log in and see if it's available to you as a user. If you don't see it, it may not offered for your utility.

**Comment by akoebbe** [comment]
Correct. There's no mention of current day usage. They used to have it via a homegrown API, but it looks like they are leaning heavily on Opower for reporting these days. Wouldn't surprise me if the utility's in-house development team was much smaller these days. I'll keep my eye on things and see if they start surfacing any real-time(ish) data on their customer portal. If they do, I'll know where to start.
