### ISSUE TITLE
Quick question on utility class naming

### ISSUE THREAD

**Issue by akoebbe** [tronikos/opower#5]
I'm starting to work on an integration with the Kansas City power utility, Evergy. It was formerly known as KCP&L (Kansas City Power and Light) and the Opower subdomain is "kcpk" (I think someone might have typo'd that and it stuck). So would you recommend I name the file and class "evergy", the actual utility name, or "kcpk", the Opower subdomain?

**Comment by tronikos** [comment]
I'd go with evergy but up to you.

**Comment by akoebbe** [comment]
I'm leaning that way as well. Thanks for the input. I'll send over a PR once I have it working.

**Comment by tronikos** [comment]
All other utility files are named after the actual utility domain which in your case seems to be evergy.com so let's stick to that convention.
